version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.7
  aws-ecr: circleci/aws-ecr@dev:alpha
  circle-compare-url: iynere/compare-url@0.4.5

executors:
  ci-base:
    resource_class: small
    docker:
      - image: cibuilds/base

  cli:
    resource_class: small
    docker:
      - image: circleci/circleci-cli

  lint-condo:
    resource_class: small
    docker:
      - image: singapore/lint-condo

jobs:
  lint:
    executor: lint-condo
    steps:
      - checkout
      - run: yamllint .

  validate:
    executor: cli
    steps:
      - checkout
      - run: circleci orb validate src/@orb.yml

  publish-dev:
    executor: cli
    steps:
      - checkout

      - run:
          name: publish dev versions
          command: |
            # for integration testing
            circleci orb publish src/@orb.yml circleci/aws-ecr@dev:alpha --token $CIRCLE_TOKEN

            # for transparency
            circleci orb publish src/@orb.yml circleci/aws-ecr@dev:$CIRCLE_BRANCH-${CIRCLE_SHA1:0:7} --token $CIRCLE_TOKEN

            # for potentially promoting to prod
            circleci orb publish src/@orb.yml circleci/aws-ecr@dev:${CIRCLE_SHA1:0:7} --token $CIRCLE_TOKEN

      - store_artifacts:
          path: src/@orb.yml

  trigger-integration:
    executor: ci-base
    parameters:
      tag:
        type: enum
        default: "integration"
        enum: ["integration", master]
    steps:
      - checkout

      - add_ssh_keys:
          fingerprints:
            - "54:b8:9b:79:74:29:3e:dd:95:52:4d:4b:e6:8b:38:f2"

      - run:
          name: git config
          command: |
            git config --global user.email "$CIRCLE_USERNAME@users.noreply.github.com"
            git config --global user.name "$CIRCLE_USERNAME"

      - circle-compare-url/reconstruct

      - run:
          name: trigger integration workflow, possible patch / minor / major release
          command: |
            CIRCLE_COMPARE_URL=$(cat CIRCLE_COMPARE_URL.txt)

            COMMIT_RANGE=$(echo $CIRCLE_COMPARE_URL | sed 's:^.*/compare/::g')

            echo "Commit range: $COMMIT_RANGE"

            if [[ $(git diff $COMMIT_RANGE --name-status | grep -e "src/@orb.yml") ]]; then
              INTEGRATION_TAG=<<parameters.tag>>-minor-$CIRCLE_BRANCH-${CIRCLE_SHA1:0:7}
            else
              INTEGRATION_TAG=<<parameters.tag>>-patch-$CIRCLE_BRANCH-${CIRCLE_SHA1:0:7}
            fi

            git tag $INTEGRATION_TAG
            git push origin $INTEGRATION_TAG

  dev-promote-prod:
    executor: cli
    parameters:
      release:
        type: enum
        default: "patch"
        enum: ["patch", "minor", "major"]
    steps:
      - run:
          name: minor release if changes to src/@orb.yml, otherwise patch
          command: circleci orb publish promote circleci/aws-ecr@dev:${CIRCLE_SHA1:0:7} <<parameters.release>> --token $CIRCLE_TOKEN

# yaml anchors
integration-dev_filters: &integration-dev_filters
  branches:
    ignore: /.*/
  tags:
    only: /integration-.*/

integration-master_filters: &integration-master_filters
  branches:
    ignore: /.*/
  tags:
    only: /master-.*/

integration-post-steps: &integration-post-steps
  [run: "aws ecr delete-repository --repository-name aws-ecr-orb-${CIRCLE_SHA1:0:7} --force", add_ssh_keys: {fingerprints: ["54:b8:9b:79:74:29:3e:dd:95:52:4d:4b:e6:8b:38:f2"]}, run: "git config --global user.email $CIRCLE_USERNAME@users.noreply.github.com && git config --global user.name $CIRCLE_USERNAME", run: "git push --delete origin $CIRCLE_TAG"]

workflows:
  lint_validate_deploy-dev:
    jobs:
      - lint

      - validate:
          requires:
            - lint

      - publish-dev:
          context: orb-publishing
          requires:
            - validate

      - trigger-integration:
          name: trigger-integration-dev
          requires:
            - publish-dev
          filters:
            branches:
              ignore: master

      - trigger-integration:
          name: trigger-integration-master
          tag: master
          requires:
            - publish-dev
          filters:
            branches:
              only: master

  integration-tests_deploy-prod:
    jobs:
      # triggered by non-master branch commits
      - aws-ecr/build_and_push_image:
          name: integration-tests-dev
          context: orb-publishing
          repo: aws-ecr-orb-${CIRCLE_SHA1:0:7}
          create-repo: true
          tag: integration-dev
          extra-build-args: --compress
          filters: *integration-dev_filters
          post-steps: *integration-post-steps

      # triggered by master branch commits
      - aws-ecr/build_and_push_image:
          name: integration-tests-master
          context: orb-publishing
          repo: aws-ecr-orb-${CIRCLE_SHA1:0:7}
          create-repo: true
          tag: integration-master
          extra-build-args: --compress
          filters: *integration-master_filters
          post-steps: *integration-post-steps

      # patch, minor, or major publishing
      - dev-promote-prod:
          name: dev-promote-patch
          context: orb-publishing
          requires:
            - integration-tests-master
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-patch.*/

      - dev-promote-prod:
          name: dev-promote-minor
          release: minor
          context: orb-publishing
          requires:
            - integration-tests-master
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-minor.*/
