description: >
  Select what Docker image to run your jobs in. By default, this orb's included jobs will use our Next Generation CircleCI Python Convenience image with the -node varient for maximum compatability.

parameters:
  image:
    type: string
    default: "cimg/python:3.8-node"
docker:
  - image: <<parameters.image>>
