description: >
  CircleCI's Ubuntu-based machine executor VM:
  https://circleci.com/docs/2.0/executor-types/#using-machine

parameters:
  image:
    type: string
    default: ubuntu-2004:202010-01
  use-docker-layer-caching:
    type: boolean
    default: false

machine:
  image: <<parameters.image>>
  docker_layer_caching: <<parameters.use-docker-layer-caching>>
